# Fix color issue.
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ",xterm*:RGB"

# Enable mouse support
set -g mouse on

# Status bar settings
set -g status-position bottom

# Set prefix to CTRL + SPACE 
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set VI mode
set-window-option -g mode-keys vi

# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# SHIFT + ALT + H/L for previous and next window
bind -n M-H previous-window
bind -n M-L next-window

# Kill all window but the current
bind * kill-window -a

# Open window in using current directory
bind c new-window -c '#{pane_current_path}'

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tyetyetye/kanagawa-tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
